on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # build step

      - name: Install dependencies
        uses: pnpm/action-setup@v6
        run: pnpm ci

      - name: Build site
        run: pnpm astro build

      # deploy

      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with:
          nekoweb-api-key: ${{ secrets.API_KEY }}
          nekoweb-domain: "wireless.fish"
          nekoweb-username: "sharkyfur"
          directory: "dist"
